### PR TITLE
new: added support for printing stats.

### PR DESCRIPTION
**Pull request by FedeDP**
Moreover, bumped golang to 1.21.

### CODE REVIEW

**Comment by FedeDP** [comment]
example output:
```
...
...

* build(deps): Bump submodules/falcosecurity-rules from `0d0e333` to `9126bef` [[#2697](https://github.com/falcosecurity/falco/pull/2697)] - [@dependabot[bot]](https://github.com/apps/dependabot)
* build(deps): Bump certifi from 2022.12.7 to 2023.7.22 in /test [[#2696](https://github.com/falcosecurity/falco/pull/2696)] - [@dependabot[bot]](https://github.com/apps/dependabot)

### Statistics

|   MERGED PRS    | NUMBER |
|-----------------|--------|
| Not user-facing |     45 |
| Release note    |     38 |
| Total           |     83 |
```

**Comment by FedeDP** [comment]
@leodido 
I can also add a build and release CI if you wish, perhaps in another PR :)

**Comment by FedeDP** [comment]
Also, it would be great to provide a reusable github action; imagine it being used like:

```
uses: actions/rn2md
with:
  token: ...
  repo:
  milestone:
  output: path.txt
```

**Review by leodido — APPROVED** [review]
Grazie Federico!

**Comment by leodido** [comment]
> @leodido I can also add a build and release CI if you wish, perhaps in another PR :)

Would love that 🙏 

See #7

**Pull request merged**
